class SCSUIncrementalEncoder:
    def __init__(self, errors: str = "strict") -> None: ...
    def encode(self, s: str, final: bool = False) -> bytes: ...

class SCSUIncrementalDecoder:
    def __init__(self, errors: str = "strict") -> None: ...
    def decode(self, s: bytes, final: bool = False) -> str: ...
