# syntax=docker/dockerfile:1
FROM ubuntu:noble

RUN yes | unminimize
RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends ca-certificates locales curl vim nano less keepassxc ssss xxd mc man manpages libimage-exiftool-perl \
    && rm -Rf /var/lib/apt/lists/* \
    && locale-gen "en_US.UTF-8" \
    && update-alternatives --set editor /usr/bin/mcedit

USER ubuntu:ubuntu
WORKDIR /app
ENV LANG="en_US.UTF-8"
ENV HOME="/home/ubuntu"
ENV PYTHON_GIL=1

ADD --chown=ubuntu:ubuntu vimrc $HOME/.vim/vimrc
ADD --chown=ubuntu:ubuntu bin.env $HOME/.soda/bin.env
ADD --chown=ubuntu:ubuntu ru.env $HOME/.soda/ru.env
ADD --chown=ubuntu:ubuntu unset.sh $HOME/.soda/unset.sh

ADD --chown=ubuntu:ubuntu https://astral.sh/uv/install.sh uv-installer.sh
RUN sh uv-installer.sh && rm uv-installer.sh
ENV PATH="/home/ubuntu/.local/bin/:$PATH"

RUN uv tool install --no-cache "rtty-soda[cli]"
RUN uv tool install --no-cache "steganon[cli]"

RUN echo "set -a" >> $HOME/.bashrc